service:
  name: serverless-slackbot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, self:custom.defaultRegion}
  profile: ${opt:profile, self:custom.defaultProfile}
  stage: ${opt:stage, self:custom.defaultStage}
  logRetentionInDays: 30

custom:
  defaultStage: dev
  defaultProfile: default
  defaultRegion: ap-northeast-1
  webpack:
    includeModules: true

functions:
  hello:
    handler: src/index.entrypoint
    timeout: 20
    events:
      - http:
          path: api/messages
          method: post
    environment:
      CLIENT_SIGNING_SECRET: ${file(./setting.yml):CLIENT_SIGNING_SECRET}
      BOT_TOKEN: ${file(./setting.yml):BOT_TOKEN}
      VERIFICATION_TOKEN: ${file(./setting.yml):VERIFICATION_TOKEN}
